# Generated by Django 5.1.7 on 2025-12-26 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('turi', models.CharField(choices=[('tolov', 'To‘lov'), ('yechib', 'Yechib olish')], max_length=10)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('xodim', models.CharField(max_length=255)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='api.talaba')),
            ],
        ),
    ]
