# Generated by Django 6.0 on 2026-01-02 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qarzdor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('balans', models.DecimalField(decimal_places=2, max_digits=12)),
                ('davr_jami', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jami_qarz', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guruh', models.CharField(max_length=100)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('holati', models.CharField(choices=[('faol', 'Faol'), ('arxiv', 'Arxivlangan')], default='faol', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='talaba',
            name='balans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talaba',
            name='ism',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talaba',
            name='telefon',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('click', 'Click'), ('payme', 'Payme'), ('bank', 'Bank hisobi'), ('uzum', 'Uzum'), ('humo', 'Humo')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='IshHaqqi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maosh_turi', models.CharField(choices=[('oylik', 'Oylik'), ('soatlik', 'Soatlik'), ('bonus', 'Bonus')], max_length=20)),
                ('miqdori', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kurs', models.CharField(max_length=100)),
                ('guruh', models.CharField(max_length=100)),
                ('oqituvchi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='QarzMiqdori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField(auto_now_add=True)),
                ('qarzdor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarzlar', to='api.qarzdor')),
            ],
        ),
    ]
